name: Main
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: docker://culturehq/actions-bundler:latest
        with:
          args: install
      - name: Test
        uses: docker://culturehq/actions-bundler:latest
        with:
          args: exec rake test
        env:
          DATABASE_URL: postgres://postgres:@127.0.0.1:5432
          REDIS_URL: redis://127.0.0.1:6379/0
          RAILS_ENV: test
