name: Main
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@master
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo snap install ruby --classic
          sudo apt-get install --no-install-recommends -y bundler nodejs yarn
      - name: Bundle install
        run: |
          pwd
          bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Yarn
        run: yarn
      - name: test
        run: |
          bundle exec rails db:prepare
          bundle exec rails test
        env:
          DATABASE_URL: postgres://postgres:@127.0.0.1:5432
          REDIS_URL: redis://127.0.0.1:6379/0
          RAILS_ENV: test
