name: Main
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
        - 5432/tcp
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Bundle install
        uses: andrewmcodes/rails-test-runner-action@master
        with:
          args: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: andrewmcodes/rails-test-runner-action@master
        with:
          args: yarn install

      - name: Run tests
        uses: andrewmcodes/rails-test-runner-action@master
        with:
          args: bundle exec rails db:prepare && bundle exec rails test
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PORT: ${{ job.services.postgres.ports[5432] }}
          PG_PASSWORD: ""
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
