name: rubocop
on: [pull_request]
jobs:
  lint:
    name: Reviewdog Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: rubocop
        uses: mgrachev/action-rubocop@master
        with:
          github_token: ${{ secrets.github_token }}
