name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: andrewmcodes/rails-test-environment:latest
      env:
        PG_HOST: 'postgres'
        PG_USER: postgres
        PG_PORT: 5432
        REDIS_URL: redis://redis:6379/0
        RAILS_ENV: test
        SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
        DISABLE_SPRING: 1
      volumes:
        - /usr/actions-playground/vendor/cache
        - /usr/actions-playground/node_modules
        - bundle:/usr/local/bundle

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
      webdriver_chrome:
        image: selenium/standalone-chrome-debug:3.0.1-germanium
        ports: ['4444:4444', '5900:5900']

    steps:
      - uses: actions/checkout@master
      - name: chromedriver?
        run: |
          unzip /usr/local/bin/chromedriver
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          bundle install --path vendor/bundle --jobs 4 --retry 3
          yarn install

      - name: Run tests
        run: |
          bin/rails db:test:prepare
          bin/rails test -p
          bin/rails test:system
        env:
          SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
      - name: Slack Notifier
        uses: k0kubun/action-slack@v1.0.0
        with:
          payload: |
            {
              "attachments": [{
                "title": "${{ job.status }}: ${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks",
                "text": "${{ github.repository }}@${{ github.ref }}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                "fields": [{ "value": ${{ toJson(github.event.head_commit.message) }}, "short": false }],
                "footer": "${{ github.event.head_commit.committer.name }} at ${{ github.event.head_commit.timestamp }}",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure() && github.event_name == 'push'
